name: cerb-${CERB_ENV:-docker}

services:
  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    ports:
      - "${CERB_PORT:-8080}:80"
    depends_on:
      - php-fpm
    environment:
      NGINX_HOST: ${CERB_HOSTNAME:-localhost}
    volumes:
      - ./nginx/cerb.conf.template:/etc/nginx/templates/cerb.conf.template
      - ./nginx/cerb.install.${CERB_INSTALL:-no}.conf:/etc/nginx/cerb.install.conf
  php-fpm:
    image: cerb/cerb:${CERB_VERSION:-latest}
    depends_on:
      - mysql
    environment:
      CERB_DB_HOST: ${MYSQL_HOST:-mysql}
      CERB_DB_NAME: ${MYSQL_DATABASE:-cerb}
      CERB_DB_USER: ${MYSQL_USER:-cerb}
      CERB_DB_PASS: ${MYSQL_PASSWORD:-s3cr3t}
      CERB_INSTALL: ${CERB_INSTALL:-}
      CERB_PROXY_HOST: ${CERB_PROXY_HOST:-}
      CERB_PROXY_PORT: ${CERB_PROXY_PORT:-}
      CERB_SERVICE_TOKEN: ${CERB_SERVICE_TOKEN:-s3cr3t}
      CERB_SERVICE_TOKEN_SCOPE: ${CERB_SERVICE_TOKEN_SCOPE:-cron update}
    volumes:
      - storage:/var/www/html/storage
      #- ./php-fpm/www.conf:/etc/php/8.5/fpm/pool.d/www.conf
  mysql:
    image: mysql:${MYSQL_VERSION:-8.4}
    command: >
      --mysql-native-password=ON
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-cerb}
      MYSQL_USER: ${MYSQL_USER:-cerb}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-s3cr3t}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  storage:
