name: cerb-docker

services:
  caddy:
    image: caddy:latest
    ports:
      - "${CERB_PORT:-80}:80"
      - "${CERB_PORT_SSL:-443}:443"
    cap_add:
       - NET_ADMIN
    depends_on:
      - cerb
    environment:
      CERB_HOSTNAME: ${CERB_HOSTNAME:-localhost}
      CERB_INSTALL: ${CERB_INSTALL:-}
      CERB_PORT_SSL: ${CERB_PORT_SSL:-443}
    volumes:
      - ./caddy/:/etc/caddy
      - caddy_config:/config
      - caddy_data:/data
  cerb:
    image: cerb/cerb:${CERB_VERSION:-latest}
    depends_on:
      - mysql
      #- redis
    environment:
      CERB_AUTHORIZED_IPS: ${CERB_AUTHORIZED_IPS}
      CERB_DB_HOST: ${MYSQL_HOST:-mysql}
      CERB_DB_NAME: ${MYSQL_DATABASE:-cerb}
      CERB_DB_USER: ${MYSQL_USER:-cerb}
      CERB_DB_PASS: ${MYSQL_PASSWORD:-s3cr3t}
      CERB_INSTALL: ${CERB_INSTALL:-}
      CERB_PROXY_HOST: ${CERB_PROXY_HOST:-}
      CERB_PROXY_PORT: ${CERB_PROXY_PORT:-}
    volumes:
      - storage:/mnt/storage
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/z-cerb.conf
  mysql:
    image: mysql:8.4
    command: >
      --mysql-native-password=ON
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-cerb}
      MYSQL_USER: ${MYSQL_USER:-cerb}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-s3cr3t}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - db:/var/lib/mysql
  #redis:
  #  image: redis:latest

volumes:
  caddy_config:
  caddy_data:
  db:
  storage:
